version: 2
aliases:
  - &envinfo
    name: Run envinfo
    command: |
      npx envinfo

jobs:
  ubuntu-test:
    working_directory: ~/repo
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Check Node installation
          environment:
            NODE_MAJOR: 20
          command: |
            apt-get update
            apt-get install -y ca-certificates curl gnupg
            apt install nodejs -y
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor > /etc/apt/keyrings/nodesource.gpg
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
            apt-get update
            apt-get install nodejs -y      
      - run: *envinfo
  debian-test:
    working_directory: ~/repo
    docker:
      - image: debian
    steps:
      - checkout
      - run:
          name: Check Node installation
          environment:
            NODE_MAJOR: 20
          command: |
            apt-get update
            apt-get install -y ca-certificates curl gnupg
            apt install nodejs -y
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor > /etc/apt/keyrings/nodesource.gpg
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
            apt-get update
            apt-get install nodejs -y      
      - run: *envinfo
  amazonlinux-test:
    working_directory: ~/repo
    docker:
      - image: amazonlinux:2023
    steps:
      - checkout
      - run:
          name: Check Node installation
          environment:
            NODE_MAJOR: 20
          command: |
            yum install https://rpm.nodesource.com/pub_${NODE_MAJOR}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
            yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
      - run: *envinfo
  fedora-test:
    working_directory: ~/repo
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
          name: Check Node installation
          environment:
            NODE_MAJOR: 20
          command: |
            yum install https://rpm.nodesource.com/pub_${NODE_MAJOR}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
            yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
      - run: *envinfo

workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu-test
      - debian-test
      - amazonlinux-test
      - fedora-test
